AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-ts-powertools-app

  Sample SAM Template for sam-ts-powertools-app

Globals:
  Api:
    OpenApiVersion: 3.0.2
    TracingEnabled: true
  Function:
    Handler: app.lambdaHandler
    Runtime: nodejs20.x
    Architectures:
      - arm64
    Timeout: 30
    MemorySize: 128
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
    Environment:
      Variables:
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
        AWS_XRAY_CONTEXT_MISSING: 'LOG_ERROR'
        POWERTOOLS_LOG_LEVEL: DEBUG
        POWERTOOLS_METRICS_NAMESPACE: sam-ts-powertools-app
        POWERTOOLS_SERVICE_NAME: helloWorld
        POWERTOOLS_TRACER_CAPTURE_HTTPS_REQUESTS: true
        POWERTOOLS_TRACER_CAPTURE_RESPONSE: true

Resources:
  GreetingTable:
    Type: AWS::Serverless::SimpleTable
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TableName: !Sub ${AWS::StackName}-Workshop
      PrimaryKey:
        Name: PK
        Type: String
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  GetGreetingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Environment:
        Variables:
          TABLE_NAME: !Ref GreetingTable
      Events:
        Greeting:
          Type: Api
          Properties:
            # RestApiId: !Ref MainApi
            Path: /greeting/{country}
            Method: get
            RequestParameters:
              - method.request.path.id:
                  Required: true
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref GreetingTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
        EntryPoints:
          - src/function/get-greeting/app.ts

  PutGreetingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Environment:
        Variables:
          TABLE_NAME: !Ref GreetingTable
      Events:
        Greeting:
          Type: Api
          Properties:
            Path: /greeting/{country}
            Method: put
            RequestParameters:
              - method.request.path.id:
                  Required: true
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref GreetingTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        EntryPoints:
          - src/function/put-greeting/app.ts

Outputs:
  # HelloWorldApi:
  #   Description: API Gateway endpoint URL for Prod stage for Hello World function
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  GetGreetingFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt GetGreetingFunction.Arn
